// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1svOkxcG9iSOh1fWpXfMSLs255ZVK3KI',
    appId: '1:1097935473525:web:21c2710ad7b65a0bdd213c',
    messagingSenderId: '1097935473525',
    projectId: 'capacitaciones-1adfd',
    authDomain: 'capacitaciones-1adfd.firebaseapp.com',
    databaseURL: 'https://capacitaciones-1adfd-default-rtdb.firebaseio.com',
    storageBucket: 'capacitaciones-1adfd.firebasestorage.app',
    measurementId: 'G-V0WL6FPN48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF9KhjzisvmE-NBraR6svcY_QYmGupRcg',
    appId: '1:1097935473525:android:53a5235fdd02364bdd213c',
    messagingSenderId: '1097935473525',
    projectId: 'capacitaciones-1adfd',
    databaseURL: 'https://capacitaciones-1adfd-default-rtdb.firebaseio.com',
    storageBucket: 'capacitaciones-1adfd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKaCsuh4c702ArSojbvXRG7Hl9fsoAJb0',
    appId: '1:1097935473525:ios:4309afdbb3499a81dd213c',
    messagingSenderId: '1097935473525',
    projectId: 'capacitaciones-1adfd',
    databaseURL: 'https://capacitaciones-1adfd-default-rtdb.firebaseio.com',
    storageBucket: 'capacitaciones-1adfd.firebasestorage.app',
    androidClientId: '1097935473525-5bu013kbhuv1gplevq374vvaf8bss0f9.apps.googleusercontent.com',
    iosClientId: '1097935473525-2ajkfaaclj3n3hs5h06674q0l6qvm0fk.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKaCsuh4c702ArSojbvXRG7Hl9fsoAJb0',
    appId: '1:1097935473525:ios:4309afdbb3499a81dd213c',
    messagingSenderId: '1097935473525',
    projectId: 'capacitaciones-1adfd',
    databaseURL: 'https://capacitaciones-1adfd-default-rtdb.firebaseio.com',
    storageBucket: 'capacitaciones-1adfd.firebasestorage.app',
    androidClientId: '1097935473525-5bu013kbhuv1gplevq374vvaf8bss0f9.apps.googleusercontent.com',
    iosClientId: '1097935473525-2ajkfaaclj3n3hs5h06674q0l6qvm0fk.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1svOkxcG9iSOh1fWpXfMSLs255ZVK3KI',
    appId: '1:1097935473525:web:6f7670ceef0c1e03dd213c',
    messagingSenderId: '1097935473525',
    projectId: 'capacitaciones-1adfd',
    authDomain: 'capacitaciones-1adfd.firebaseapp.com',
    databaseURL: 'https://capacitaciones-1adfd-default-rtdb.firebaseio.com',
    storageBucket: 'capacitaciones-1adfd.firebasestorage.app',
    measurementId: 'G-7RBNCRSYWX',
  );

}