// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxRiHm9nBU6TXLVw9oSJfN_GCmgAOXCJc',
    appId: '1:45147920639:web:6518b5e531dd00fcc7d4ca',
    messagingSenderId: '45147920639',
    projectId: 'dashapp-69a70',
    authDomain: 'dashapp-69a70.firebaseapp.com',
    storageBucket: 'dashapp-69a70.firebasestorage.app',
    measurementId: 'G-50EJN5KWN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_ZyBxl4PiOjHWx-Mhs8isjRxmJy7bH8Q',
    appId: '1:45147920639:android:a86557006569e13cc7d4ca',
    messagingSenderId: '45147920639',
    projectId: 'dashapp-69a70',
    storageBucket: 'dashapp-69a70.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxRiHm9nBU6TXLVw9oSJfN_GCmgAOXCJc',
    appId: '1:45147920639:web:a3c658b78d1e914dc7d4ca',
    messagingSenderId: '45147920639',
    projectId: 'dashapp-69a70',
    authDomain: 'dashapp-69a70.firebaseapp.com',
    storageBucket: 'dashapp-69a70.firebasestorage.app',
    measurementId: 'G-VYKNHRLFJV',
  );

}